---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: google-pause
  namespace: demo
  labels:
    app: google-pause
  annotations:
    flux.weave.works/automated: "false"
spec:
  strategy:
    rollingUpdate:
      maxUnavailable: 0
    type: RollingUpdate
  selector:
    matchLabels:
      app: pause
  template:
    metadata:
      labels:
        app: pause
    spec:
      containers:
      - name: pause
        image: google/pause:latest
        imagePullPolicy: IfNotPresent
