---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pacman
  namespace: project-a
  labels:
    app: pacman
  annotations:
    flux.weave.works/automated: "true"
spec:
  strategy:
    rollingUpdate:
      maxUnavailable: 0
    type: RollingUpdate
  selector:
    matchLabels:
      app: pacman
  template:
    metadata:
      labels:
        app: pacman
    spec:
      containers:
      - name: pacman
        image: nbaillie/pacman:latest
        imagePullPolicy: IfNotPresent
