apiVersion: v1
kind: Service
metadata:
  name: pacman
  namespace: project-a
  labels:
    app: pacman
spec:
  type: ClusterIP
  selector:
    app: pacman
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: http
